name: flutter-analyze-commenter example

on: pull_request # flutter-analyze-commenter only supports run by pull request

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # required to add comment on PR
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - run: flutter pub get

      # run flutter analyze with --write option
      - run: flutter analyze --write=flutter_analyze.log

      # (Optional)run custom lint with --format=json option
      - if: ${{ !cancelled() }}
        run: dart run custom_lint --format=json > custom_lint.json

      # use flutter-analyze-commenter
      - uses: yorifuji/flutter-analyze-commenter@v1
        if: ${{ !cancelled() }} # required to run this step even if flutter analyze fails
        with:
          analyze-log: flutter_analyze.log # file path for analyze log
          custom-lint-log: custom_lint.log # file path for custom lint log (optional)
          verbose: false # verbose output (optional)
